spring.application.name=SpringAI
server.port = 8081

# api-key for openAI present inside the enviroment variables
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.models=gpt-4o-mini
spring.ai.openai.chat.options.temperature=0.2
