spring.application.name=SpringAI
server.port = 8081

# api-key for openAI present inside the enviroment variables
#spring.ai.openai.api-key=${OPENAI_API_KEY}
#spring.ai.openai.chat.options.models=gpt-4o-mini
#spring.ai.openai.chat.options.temperature=0.2


# ollama qwen3:30b 18GB
spring.ai.ollama.base-url=https://localhost:11434
spring.ai.ollama.chat.options.model=qwen3:30b
spring.ai.ollama.chat.options.temperature=0.2
